apiVersion: v1
kind: ConfigMap
metadata:
  name: crocodile-stress-test
  labels:
    app.kubernetes.io/part-of: argocd
    annotations:
    argocd.argoproj.io/sync-wave: "0"

data:
  new.js: |+
    import http from 'k6/http';
    import { group, check } from 'k6';
    export const options = {
      stages: [
        { target: 40, duration: '20s' },
        { target: 0, duration: '20s' },
      ],
    };
    export default function () {
      group('get crocodiles', function () {
      const result = http.get('https://test-api.k6.io/public/crocodiles/');
      check(result, {
        'http response status code is 200': result.status === 200,
      });
      });

      group('get testk6', function () {
      const result1 = http.get('https://test.k6.io');
      check(result1, {
        'http response status code is 200': result1.status === 200,
      });
      });
      
    }