apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  parallelism: 3
  script:
    configMap:
      name: crocodile-stress-test
      file: new.js